### ISSUE TITLE
MGDB_user not found. Declare it as envvar or define a default value.

### ISSUE THREAD

**Issue by cmporeddy** [dc-aichara/COVID19-India-Tracker#3]
line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: MGDB_user not found. Declare it as envvar or define a default value.

**Comment by dc-aichara** [comment]
@cmporeddy 
This means, you don't have `MGDB_user` defined in `.env` file. You can't use MongDB. You have to use local storage.
You have to edit data.py to use local storage instead of MongoDB.

**Comment by cmporeddy** [comment]
Thank you so much for your quick response. You mean I need to use `api_india.csv` & `states.csv`?

Is there any sample code of `data.py` that I can try?**[local storage]** I am learning python. I am trying to understand this project.

**Comment by dc-aichara** [comment]
You have to edit `https://github.com/dc-aichara/COVID19-India-Tracker/commits/master/data/data.py` to save and load data from local storage (your laptop). For more information, see change history of `data/data.py`.

**Comment by cmporeddy** [comment]
I will check that, Thankyou

**Comment by cmporeddy** [comment]
I tried as you said, but I don't see any data coming in the webpage. 
<img width="1440" alt="Screen Shot 2021-04-19 at 12 40 37 AM" src="https://user-images.githubusercontent.com/59572733/115153372-27f13080-a0a8-11eb-932e-03529c2a5727.png">

**Comment by cmporeddy** [comment]
```
mgdb_user = config("MGDB_user")
mgcb_pass = config("MGDB_pass") 
```

where can I get these credientials?

**Comment by cmporeddy** [comment]
I added `MGDB_user` & `MGDB_pass` & I changed the URL according to my DB, & added my IP in the whitelist, I still get the same error.
**ERROR**
 `line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: testinguser not found. Declare it as envvar or define a default value.
`

**Comment by dc-aichara** [comment]
Can you check if you have defined variables correctly in `settings.ini` as follows? `settings.ini` should be inside the `COVID19-India-Tracker` directory. 

```
[settings]
MAPBOX_SECRET=Your_key
MAPBOX_STYLE=mapbox://styles/mapbox/dark-v9
MGDB_pass=your_pass
MGDB_user=your_username
```

**Comment by cmporeddy** [comment]
yes, I did the same, I even tried including `MGDB_user` & `MGDB_pass` directly in the URL, still no luck :(

**Comment by cmporeddy** [comment]
WoW, Now it's working .... . . . . THANK YOU SO MUCH
